# Generated by Django 3.0.7 on 2020-07-06 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200628_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='https://api.adorable.io/avatars/face/eyes6/nose4/mouth3/B3D457', max_length=200, upload_to='perfil/', verbose_name='Foto de perfil'),
        ),
    ]
