# Generated by Django 3.0.7 on 2020-07-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200706_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/default.png', max_length=200, upload_to='media/', verbose_name='Foto de perfil'),
        ),
    ]
